name: C++ CI Build & Test

on:
  push:
    branches: [main, CICD_Agent, '**']
  pull_request:
    branches: [main, CICD_Agent, '**']

jobs:
  build-test:
    name: Build and Test (C++ Matrix)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup C++ Compiler
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y build-essential cmake
          else
            sudo apt-get install -y clang cmake
          fi

      - name: Setup C++ Compiler (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            echo "Using clang (default on macOS)"
          fi

      - name: Setup C++ Compiler (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Create Build Directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cmake .. -G "Visual Studio 17 2022"
          else
            cmake ..
          fi

      - name: Build
        working-directory: build
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cmake --build . --config Release
          else
            cmake --build .
          fi

      - name: Run Tests
        working-directory: build
        run: |
          if [[ -f "CTestTestfile.cmake" ]]; then
            ctest --output-on-failure
          else
            echo "No tests found. Please add tests with CTest, Google Test, or Catch2."
          fi

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.compiler }}
          path: build/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.compiler }}
          path: build/Testing/Temporary/LastTest.log

    # Optionally add code coverage and static analysis steps here
